version: '2'

services:
  app:
    build: .
    ports:
      - '5001:3000'
  chrome:
    build:
      context: .
      dockerfile: chrome.Dockerfile
    cap_add:
      - SYS_ADMIN
    ports:
      - '5002:9222'