version: '2'

services:
  app:
    command: npm run dev
    ports:
      - '9229:9229'
    volumes:
      - .:/app
      - ~/Dev/contributions/thirdparty/html-pdf-chrome:/app/node_modules/html-pdf-chrome
      - /app/node_modules